# Variables
title:         "Badge"
description:   "Display a badge element in front of another Bulma element with different colors."
version:       3.0.0
# url:           https://demo.creativebulma.net/elements/badge/

# Build
markdown:      kramdown
permalink:     pretty
includes:      ['assets/css', 'assets/js']
exclude:       ['package.json']
sass:
  sass_dir:    _sass
  style:       compressed
